# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 GhostBlade Project

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(GHOSTBLADE_AARCH64_TRIPLE "$ENV{GHOSTBLADE_AARCH64_CROSS_COMPILE}")
if(NOT GHOSTBLADE_AARCH64_TRIPLE)
  set(GHOSTBLADE_AARCH64_TRIPLE "aarch64-linux-gnu-")
endif()

set(CMAKE_C_COMPILER   "${GHOSTBLADE_AARCH64_TRIPLE}gcc")
set(CMAKE_CXX_COMPILER "${GHOSTBLADE_AARCH64_TRIPLE}g++")
set(CMAKE_ASM_COMPILER "${GHOSTBLADE_AARCH64_TRIPLE}gcc")
set(CMAKE_AR           "${GHOSTBLADE_AARCH64_TRIPLE}ar")
set(CMAKE_RANLIB       "${GHOSTBLADE_AARCH64_TRIPLE}ranlib")
set(CMAKE_STRIP        "${GHOSTBLADE_AARCH64_TRIPLE}strip")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
