# SPDX-License-Identifier: MIT
# Copyright (C) 2026 GhostBlade Project

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m33)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(GHOSTBLADE_ARM_TRIPLE "$ENV{PICO_TOOLCHAIN_PATH}")
if(GHOSTBLADE_ARM_TRIPLE)
  set(_GHOSTBLADE_ARM_PREFIX "${GHOSTBLADE_ARM_TRIPLE}/arm-none-eabi-")
else()
  set(_GHOSTBLADE_ARM_PREFIX "arm-none-eabi-")
endif()

set(CMAKE_C_COMPILER   "${_GHOSTBLADE_ARM_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${_GHOSTBLADE_ARM_PREFIX}g++")
set(CMAKE_ASM_COMPILER "${_GHOSTBLADE_ARM_PREFIX}gcc")
set(CMAKE_AR           "${_GHOSTBLADE_ARM_PREFIX}ar")
set(CMAKE_RANLIB       "${_GHOSTBLADE_ARM_PREFIX}ranlib")
set(CMAKE_OBJCOPY      "${_GHOSTBLADE_ARM_PREFIX}objcopy")
set(CMAKE_OBJDUMP      "${_GHOSTBLADE_ARM_PREFIX}objdump")
set(CMAKE_SIZE_UTIL    "${_GHOSTBLADE_ARM_PREFIX}size")

set(PICO_PLATFORM "rp2350" CACHE STRING "Target Pico platform" FORCE)
