#ifndef _DT_BINDINGS_GPIO_GPIO_H
#define _DT_BINDINGS_GPIO_GPIO_H

#define GPIO_ACTIVE_HIGH 0
#define GPIO_ACTIVE_LOW 1

#define GPIO_PULL_UP 0
#define GPIO_PULL_DOWN 1
#define GPIO_OPEN_DRAIN 2
#define GPIO_OPEN_SOURCE 4

#endif
